export const CREATE_USER_REQ = 'SIGN_UP:SEND_CREATE_USER_REQUEST',
    AUTH_USER_REQ = 'SIGN_IN:SEND_AUTHORISE_USER_REQUEST',
    SET_USER = 'STORAGE:SET_USER',
    SET_AUTH_LOADING = "SET_AUTH_LOADING",
    CHECK_AUTH_USER = "CHECK_AUTH_USER",
    SET_AUTH = "SET_AUTH_TOGGLE"