export const CREATE_USER_REQ = 'SIGN_UP:SEND_CREATE_USER_REQUEST', //my user's types
    AUTH_USER_REQ = 'SIGN_IN:SEND_AUTHORISE_USER_REQUEST',
    SET_USER = 'STORAGE:SET_USER',
    SET_AUTH_LOADING = "SET_AUTH_LOADING",
    CHECK_AUTH_USER = "CHECK_AUTH_USER",
    SET_AUTH = "SET_AUTH_TOGGLE",
    RESET_AUTH = "RESET_AUTH_USER"

export const SET_FRIEND_TAB = "SET_FRIEND_TAB", //app types
    BLOCK_ACTIVE_TAB = "HEADER:BLOCK_ACTIVE_TAB",
    SHOW_ALERT = "SHOW_ALERT",
    SET_ALERT = "SET_ALERT",
    SHOW_MODAL = "SHOW_MODAL",
    SET_MODAL = "SET_MODAL"

export const CREATE_TASK_OR_GROUP_REQ = 'CREATING_FORM:CREATE_TASK_REQUEST', //tasks types
    SET_TASKS = "SET_TASKS",
    CHECK_TASK_REQ = "CHECK_TASK_REQ",
    DELETE_ITEM_REQ = "DELETE_ITEM_REQ",
    SET_EDITING_TASK_ID = "SET_EDITING_TASK_ID",
    EDIT_TASK_REQ = "EDIT_TASK_REQ",
    EDIT_ITEM_REQ = "EDIT_ITEM_REQ"

export const SET_NEW_GROUP = 'SET_NEW_GROUP', //group types
    SET_GROUPS = "SET_GROUPS",
    GET_GROUPS_REQ = "GET_GROUPS_REQUEST",
    GET_GROUP_REQ = "GET_GROUP_REQUEST",
    SET_OPENED_GROUP = "SET_OPENED_GROUP",
    SET_EDITING_GROUP_ID = "SET_EDITING_GROUP_ID",
    GET_GROUP_USERS_REQ = "GET_GROUP_USERS_REQ",
    SET_EDITING_GROUP_USERS = "SET_EDITING_GROUP_USERS",
    GET_DATA_FOR_GROUPS = "GET_DATA_FOR_GROUPS",
    SET_HOVERED_GROUP = 'SET_HOVERED_GROUP',
    SET_SEARCH_TEXT_FOR_GROUPS = 'SET_SEARCH_TEXT_FOR_GROUPS',
    SET_FILTER_USERS_FOR_GROUPS = 'SET_FILTER_USERS_FOR_GROUPS',
    SET_FILTER_TAGS_FOR_GROUPS = 'SET_FILTER_TAGS_FOR_GROUPS'

export const SET_USERS = 'SET_USERS',
    GET_USERS_REQ = 'GET_USERS_REQUEST',
    SET_MY_FRIENDS = 'SET_MY_FRIENDS',
    SET_MEMBERS = 'SET_MEMBERS'