export const CREATE_USER_REQ = 'SIGN_UP:SEND_CREATE_USER_REQUEST', //my user's types
    AUTH_USER_REQ = 'SIGN_IN:SEND_AUTHORISE_USER_REQUEST',
    SET_USER = 'STORAGE:SET_USER',
    SET_AUTH_LOADING = "SET_AUTH_LOADING",
    CHECK_AUTH_USER = "CHECK_AUTH_USER",
    SET_AUTH = "SET_AUTH_TOGGLE",
    RESET_AUTH = "RESET_AUTH_USER"

export const SET_HEADER_TAB = 'SET_HEADER_ACTIVE_TAB', //app types
    BLOCK_ACTIVE_TAB = "HEADER:BLOCK_ACTIVE_TAB"

export const CREATE_TASK_OR_GROUP_REQ = 'CREATING_FORM:CREATE_TASK_REQUEST', //tasks types
    SAVE_NEW_TASK = "SAVE_NEW_TASK"

export const SET_NEW_GROUP = 'SET_NEW_GROUP', //group types
    SET_GROUPS = "SET_GROUPS",
    GET_GROUPS_REQ = "GET_GROUPS_REQUEST"

export const SET_USERS = 'SET_USERS',
    GET_USERS_REQ = 'GET_USERS_REQUEST'